Add initial configuration file for Air with build settings and logging options
- Created air.toml to define build parameters, logging preferences, and color settings for the Air tool.
- Configured build commands, directories to include/exclude, and error handling options.
- Set up logging options for better visibility during development.

diff --git a/apps/backend/Taskfile.yml b/apps/backend/Taskfile.yml
--- a/apps/backend/Taskfile.yml
+++ b/apps/backend/Taskfile.yml
@@ -7,16 +7,20 @@ tasks:
   help:
     desc: print this help message
     cmds:
-    - task --list-all
+      - task --list-all
     silent: true
 
   confirm:
     desc: confirmation prompt
     cmds:
-    - |
-      echo -n 'Are you sure? [y/N] ' && read ans && [ ${ans:-N} = y ]
+      - |
+        echo -n 'Are you sure? [y/N] ' && read ans && [ ${ans:-N} = y ]
     silent: true
     internal: true
+
+  air:
+    cmds:
+      - go tool air
 
   run:
     desc: run the cmd/tasker application
@@ -28,28 +32,28 @@ tasks:
     vars:
       NAME: '{{.name | default ""}}'
     cmds:
-    - |
-      if [ -z "{{.NAME}}" ]; then
-        echo "Error: name parameter is required"
-        echo "Usage: task migrations:new name=migration_name"
-        exit 1
-      fi
-    - echo 'Creating migration file for {{.NAME}}...'
-    - tern new -m ./internal/database/migrations {{.NAME}}
+      - |
+        if [ -z "{{.NAME}}" ]; then
+          echo "Error: name parameter is required"
+          echo "Usage: task migrations:new name=migration_name"
+          exit 1
+        fi
+      - echo 'Creating migration file for {{.NAME}}...'
+      - tern new -m ./internal/database/migrations {{.NAME}}
 
   migrations:up:
     desc: apply all up database migrations
     deps: [ confirm ]
     cmds:
-    - echo 'Running up migrations...'
-    - tern migrate -m ./internal/database/migrations --conn-string {{.TASKER_DB_DSN}}
+      - echo 'Running up migrations...'
+      - tern migrate -m ./internal/database/migrations --conn-string {{.TASKER_DB_DSN}}
 
   tidy:
     desc: format all .go files, and tidy and vendor module dependencies
     cmds:
-    - echo 'Formatting .go files...'
-    - go fmt ./...
-    - echo 'Tidying module dependencies...'
-    - go mod tidy
-    - echo 'Verifying dependencies...'
-    - go mod verify
+      - echo 'Formatting .go files...'
+      - go fmt ./...
+      - echo 'Tidying module dependencies...'
+      - go mod tidy
+      - echo 'Verifying dependencies...'
+      - go mod verify
